name: Docker

on:
  push:
    branches:
      - master
env:
  VERSION: 1.9.7

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out
        uses: actions/checkout@v4
        with:
          repository: ether/etherpad-lite
          ref: 'refs/tags/${{ env.VERSION }}'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/etherpad:${{ env.VERSION }}
          build-args: |
            ETHERPAD_PLUGINS=ep_comments_page ep_author_neat ep_font_size
